"""initial migration

Revision ID: 465ab886684c
Revises:
Create Date: 2023-06-08 02:12:17.936795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "465ab886684c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "book",
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("isbn", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("author", sa.String(length=50), nullable=False),
        sa.Column("edition", sa.String(length=50), nullable=True),
        sa.Column("publisher", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("added_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_book_isbn"), ["isbn"], unique=True)
        batch_op.create_index(batch_op.f("ix_book_name"), ["name"], unique=False)

    op.create_table(
        "member",
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("second_name", sa.String(length=50), nullable=True),
        sa.Column("id_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("added_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("member", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_member_id_number"), ["id_number"], unique=True
        )

    op.create_table(
        "transaction",
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("rent_date", sa.DateTime(), nullable=True),
        sa.Column("return_date", sa.DateTime(), nullable=True),
        sa.Column("rent_amount", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("book", sa.String(length=36), nullable=True),
        sa.Column("member", sa.String(length=36), nullable=True),
        sa.Column("rented_by", sa.String(length=36), nullable=True),
        sa.Column("returned_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["book"],
            ["book.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["member"],
            ["member.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["rented_by"],
            ["user.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["returned_by"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.drop_table("tb1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb1",
        sa.Column("one", sa.TEXT(), nullable=True),
        sa.Column("two", sa.INTEGER(), nullable=True),
    )
    op.drop_table("transaction")
    with op.batch_alter_table("member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_member_id_number"))

    op.drop_table("member")
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_book_name"))
        batch_op.drop_index(batch_op.f("ix_book_isbn"))

    op.drop_table("book")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
