"""add book-quantity, transaction-rate_per_day

Revision ID: ca33df0ba773
Revises: 465ab886684c
Create Date: 2023-06-09 12:46:33.820187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca33df0ba773"
down_revision = "465ab886684c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quantity", sa.Integer(), nullable=True))

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rate_per_day", sa.Float(), nullable=True))
        batch_op.drop_column("rent_amount")
        batch_op.drop_column("status")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column("rent_amount", sa.FLOAT(), nullable=False))
        batch_op.drop_column("rate_per_day")

    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.drop_column("quantity")

    # ### end Alembic commands ###
